CREATE TABLE IF NOT EXISTS CAR_DETAILS_RAW (
    LISTING_ID STRING,
    LINK STRING,
    TEN STRING,
    GIA NUMBER,
    DIA_CHI STRING,
    SO_KM_DA_DI NUMBER,
    XUAT_XU STRING,
    TINH_TRANG STRING,
    HANG STRING,
    DONG_XE STRING,
    NAM_SAN_XUAT STRING,
    HOP_SO STRING,
    NHIEN_LIEU STRING,
    KIEU_DANG STRING,
    SO_CHO STRING,

    CRAWLED_AT TIMESTAMP_NTZ,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ACTIVE_LISTINGS_RAW (
    LISTING_ID STRING,
    LINK STRING,
    CRAWLED_AT TIMESTAMP_NTZ,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
