version: 2
sources:
  - name: raw
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: RAW
    tables:
      - name : car_details_raw
        identifier: CAR_DETAILS_RAW
      - name: active_listings_raw
        identifier: ACTIVE_LISTINGS_RAW
